#include <vector>
#include <list>
#include <map>
#include <set>
#include <deque>
#include <queue>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstring>

#define out freopen("output.txt", "w", stdout);
#define in freopen("input.txt", "r", stdin);
#define clr(arr, key) memset(arr, key, sizeof arr)
#define pb push_back
#define infinity (1 << 28)
#define LL long long
#define PI acos(-1)
#define gcd(a, b) __gcd(a, b)
#define lcm(a, b) ((a)*((b)/gcd(a,b)))
#define all(v) v.begin(), v.end()
#define no_of_ones __builtin_popcount // count 1's in a numbers binary representation
#define SZ(v) (int)(v.size())
#define eps 10e-7

//int col[8] = {0, 1, 1, 1, 0, -1, -1, -1};
//int row[8] = {1, 1, 0, -1, -1, -1, 0, 1};
//int col[4] = {1, 0, -1, 0};
//int row[4] = {0, 1, 0, -1};
//int months[13] = {0, ,31,28,31,30,31,30,31,31,30,31,30,31};

using namespace std;

#define MAX 110
/*************************************************HABIJABI ENDS HERE******************************************************/

vector <int> adj[MAX];
set <int> ss;

class GoodCompanyDivTwo {
public:
	int countGood(vector <int> superior, vector <int> workType) {
		int i, j, ret = 0;

		for(i = 0; i < SZ(superior); i++)
        {
            adj[i].clear();
            adj[i].pb(i);
        }

		for(i = 1; i < SZ(superior); i++)
            adj[superior[i]].pb(i);
        for(i = 0; i < SZ(superior); i++)
        {
//            if(SZ(adj[i]) == 0) continue;
            ss.clear();
            for(j = 0; j < SZ(adj[i]); j++)
            {
                ss.insert(workType[adj[i][j]]);
            }
            if(SZ(ss) == SZ(adj[i]))
                ret++;
        }
        return ret;
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit-pf 2.3.0
#include <iostream>
#include <string>
#include <vector>
#include <ctime>
#include <cmath>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <int> p0, vector <int> p1, bool hasAnswer, int p2) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p0[i];
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p1[i];
	}
	cout << "}";
	cout << "]" << endl;
	GoodCompanyDivTwo *obj;
	int answer;
	obj = new GoodCompanyDivTwo();
	clock_t startTime = clock();
	answer = obj->countGood(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p2 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p2;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	bool disabled;
	bool tests_disabled;
	all_right = true;
	tests_disabled = false;

	vector <int> p0;
	vector <int> p1;
	int p2;

	// ----- test 0 -----
	disabled = false;
	p0 = {-1,0};
	p1 = {1,2};
	p2 = 2;
	all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------

	// ----- test 1 -----
	disabled = false;
	p0 = {-1,0};
	p1 = {1,1};
	p2 = 1;
	all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------

	// ----- test 2 -----
	disabled = false;
	p0 = {-1,0,1,1};
	p1 = {1,4,3,2};
	p2 = 4;
	all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------

	// ----- test 3 -----
	disabled = false;
	p0 = {-1,0,1,0,0};
	p1 = {3,3,5,2,2};
	p2 = 4;
	all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------

	// ----- test 4 -----
	disabled = false;
	p0 = {-1,0,1,1,1,0,2,5};
	p1 = {1,1,2,3,4,5,3,3};
	p2 = 7;
	all_right = (disabled || KawigiEdit_RunTest(4, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------

	// ----- test 5 -----
	disabled = false;
	p0 = {-1,0,0,1,1,3,0,2,0,5,2,5,5,6,1,2,11,12,10,4,7,16,10,9,12,18,15,23,20,7,4};
	p1 = {4,6,4,7,7,1,2,8,1,7,2,4,2,9,11,1,10,11,4,6,11,7,2,8,9,9,10,10,9,8,8};
	p2 = 27;
	all_right = (disabled || KawigiEdit_RunTest(5, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------

	if (all_right) {
		if (tests_disabled) {
			cout << "You're a stud (but some test cases were disabled)!" << endl;
		} else {
			cout << "You're a stud (at least on given cases)!" << endl;
		}
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
//
// Shiny has a company.
// There are N employees in her company.
// The employees are numbered 0 through N-1 in order in which they joined the company.
//
//
//
// Employee 0 is the only employee with no boss.
// Every other employee has precisely one direct boss in the company.
// You are given a vector <int> superior with N elements.
// Element 0 of superior will be -1 to denote that employee 0 has no boss.
// For each i between 1 and N-1, inclusive, element i of superior will be the number of the boss of employee i.
//
//
//
// For each employee, their boss joined the company before them.
// Formally, for each i between 1 and N-1, inclusive, superior[i] will be between 0 and i-1, inclusive.
//
//
//
// Each employee only does one type of work.
// You are given a vector <int> workType with N elements.
// (Different integers represent different types of work.)
//
//
//
// Each employee of the company has their own department.
// The department of employee x is formed by employee x and all the employees such that x is their boss.
// Formally, for any y different from x, employee y belongs into the department of employee x if and only if superior[y]=x.
// Note that if superior[z]=y and superior[y]=x, employee z does not belong into the department of employee x.
//
//
//
// A department is called diverse if no two employees in the department do the same type of work.
// Compute and return the number of diverse departments in Shiny's company.
//
//
// DEFINITION
// Class:GoodCompanyDivTwo
// Method:countGood
// Parameters:vector <int>, vector <int>
// Returns:int
// Method signature:int countGood(vector <int> superior, vector <int> workType)
//
//
// CONSTRAINTS
// -superior will contain between 1 and 100 elements, inclusive.
// -workType will contain the same number of elements as superior.
// -Each element of workType will be between 1 and 100, inclusive.
// -superior[0] will be -1.
// -For each valid i>0, superior[i] will be between 0 and i-1, inclusive.
//
//
// EXAMPLES
//
// 0)
// {-1, 0}
// {1, 2}
//
// Returns: 2
//
// The department of employee 0 contains employees 0 and 1.
// The department of employee 1 contains employee 1 only.
// Both departments are diverse.
//
// 1)
// {-1, 0}
// {1, 1}
//
// Returns: 1
//
// The departments are the same as in Example 0.
// However, now the department of employee 0 is not diverse: it contains two employees who do the same type of work.
// Only the department of employee 1 is now diverse.
//
// 2)
// {-1, 0, 1, 1}
// {1, 4, 3, 2}
//
// Returns: 4
//
// Note that in this test case the department of employee 0 contains only employees 0 and 1. Employees 2 and 3 do not belong into the department of employee 0.
//
// 3)
// {-1, 0, 1, 0, 0}
// {3, 3, 5, 2, 2}
//
// Returns: 4
//
//
//
// 4)
// {-1, 0, 1, 1, 1, 0, 2, 5}
// {1, 1, 2, 3, 4, 5, 3, 3}
//
// Returns: 7
//
//
//
// 5)
// {-1, 0, 0, 1, 1, 3, 0, 2, 0, 5, 2, 5, 5, 6, 1, 2, 11, 12, 10, 4, 7, 16, 10, 9, 12, 18, 15, 23, 20, 7, 4}
// {4, 6, 4, 7, 7, 1, 2, 8, 1, 7, 2, 4, 2, 9, 11, 1, 10, 11, 4, 6, 11, 7, 2, 8, 9, 9, 10, 10, 9, 8, 8}
//
// Returns: 27
//
//
//
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit-pf 2.3.0!
